"""Phase 4 D-19 / C-02 / C-03: Mustache-style template rendering for campaign messages.

Supported variables (case-insensitive):
- {{name}} / {{full_name}} / {{имя}}    → contact.full_name
- {{username}} / {{юзернейм}}           → '@' + contact.username (empty if no username)
- {{phone}} / {{телефон}}               → contact.phone
- {{source}} / {{источник}}             → contact.source
- {{custom.X}}                          → contact.custom[X]  (X is English-only)
- {{компания}}                          → contact.custom['company']  (alias to custom.company)

Spaces inside braces OK: {{ name }} works.

Missing variables (2026-05-26 update):
  When a {{var}} resolves to empty/missing, the placeholder AND its surrounding
  whitespace + a single trailing/leading punctuation are stripped, so:
    "Hi {{full_name}}!"        + empty   →  "Hi!"
    "Hi {{full_name}}, how?"   + empty   →  "Hi, how?"     ← keeps "," as part of sentence
    "Hi {{full_name}}"         + "Polina" → "Hi Polina"   ← normal path unchanged
  Plus final pass collapses double spaces. Still logs warning per D-19.
No Mustache filters ({{name | upper}}) per C-03.
"""

import logging
import re
from typing import Any, Optional

logger = logging.getLogger(__name__)

# Regex per C-03: allows spaces inside braces, supports Cyrillic letters,
# dot notation for custom.X (English keys only inside the dotted suffix).
TEMPLATE_VAR_RE = re.compile(
    r"\{\{\s*([a-zA-Zа-яА-Я_][a-zA-Zа-яА-Я_0-9]*(?:\.[a-zA-Z_0-9]+)?)\s*\}\}",
    re.IGNORECASE | re.UNICODE,
)

# C-02 — Russian alias table + English aliases (lowercase keys → canonical name).
# 2026-05-26: `full_name` added as the natural English alias for `name`. Templates
# generated by humans tend to use `{{full_name}}` since that's the DB column name.
RUSSIAN_ALIASES = {
    "имя": "name",
    "юзернейм": "username",
    "телефон": "phone",
    "источник": "source",
    "компания": "custom.company",
    "full_name": "name",
    "fullname": "name",
}


def _resolve(var_name: str, contact: dict[str, Any]) -> Optional[str]:
    """Resolve {{var}} → contact field value. Returns None if missing/unknown.

    Args:
        var_name: variable name from inside braces (already lowercased).
        contact: dict with contact fields (full_name, username, phone, source, custom).

    Returns: string value or None when variable cannot be resolved.
    """
    # Apply Russian alias (lowercase keys).
    if var_name in RUSSIAN_ALIASES:
        var_name = RUSSIAN_ALIASES[var_name]

    # custom.X dotted notation.
    if "." in var_name:
        prefix, _, key = var_name.partition(".")
        if prefix != "custom":
            return None
        custom = contact.get("custom") or {}
        value = custom.get(key)
        return None if value is None or value == "" else str(value)

    if var_name == "name":
        v = contact.get("full_name")
        return None if not v else str(v)
    if var_name == "username":
        v = contact.get("username")
        if not v:
            return None
        # Prepend @ if missing.
        v_str = str(v)
        return v_str if v_str.startswith("@") else f"@{v_str}"
    if var_name == "phone":
        v = contact.get("phone")
        return None if not v else str(v)
    if var_name == "source":
        v = contact.get("source")
        return None if not v else str(v)

    return None


def render_template(
    template: str,
    contact: dict[str, Any],
    *,
    campaign_id: str = "?",
    phone: str = "?",
) -> str:
    """Render Mustache-style template with contact fields.

    When a variable resolves to empty, its surrounding whitespace and a single
    adjacent punctuation char (,/./!/?/;/:) are absorbed so the sentence stays
    natural — see module docstring for examples.

    Args:
        template: string with {{var}} placeholders.
        contact: dict with full_name / username / phone / source / custom.
        campaign_id: for warning logs (no semantic effect on render).
        phone: for warning logs (no semantic effect on render).

    Returns: rendered string (missing vars → smart-trimmed + warning per D-19).
    """
    if not template:
        return ""

    # Use a sentinel that will never appear in user content. After the first
    # substitution pass, we walk the string and absorb whitespace around each
    # sentinel. This keeps the simple regex approach but yields clean text
    # for missing variables.
    _EMPTY = "\x00EMPTY\x00"

    def replacer(match: re.Match) -> str:
        raw = match.group(1)
        value = _resolve(raw.lower(), contact)
        if value is None:
            logger.warning(
                "Template variable {{%s}} missing for contact phone=%s campaign=%s",
                raw, phone, campaign_id,
            )
            return _EMPTY
        return value

    rendered = TEMPLATE_VAR_RE.sub(replacer, template)

    if _EMPTY in rendered:
        # Collapse whitespace + single trailing OR leading punctuation around the sentinel.
        # Patterns handled (greedy left/right whitespace, optional one punct):
        #   "Hi {{x}}!"        → "Hi!"        (consume left space + nothing right)
        #   "Hi {{x}}, how?"   → "Hi, how?"   (consume left space + keep ", how?")
        #   "Hello {{x}} bye"  → "Hello bye"  (consume left+right space, single space stays)
        #   "{{x}} world"      → "world"      (consume right space when at start)
        # Step 1: " " EMPTY (punct)? " " → keep punct as text, no space
        rendered = re.sub(rf" *{re.escape(_EMPTY)} *([,.!?;:])", r"\1", rendered)
        # Step 2: " " EMPTY (rest = no adjacent punct) → " "
        rendered = re.sub(rf" *{re.escape(_EMPTY)} *", " ", rendered)
        # Step 3: collapse any double spaces produced anywhere
        rendered = re.sub(r" {2,}", " ", rendered)
        rendered = rendered.strip()

    return rendered
