/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedWarmupRouteImport } from './routes/_authenticated/warmup'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedKnowledgeBasesIndexRouteImport } from './routes/_authenticated/knowledge-bases.index'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns.index'
import { Route as AuthenticatedKnowledgeBasesIdRouteImport } from './routes/_authenticated/knowledge-bases.$id'
import { Route as AuthenticatedCampaignsNewRouteImport } from './routes/_authenticated/campaigns.new'
import { Route as AuthenticatedCampaignsIdRouteImport } from './routes/_authenticated/campaigns.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarmupRoute = AuthenticatedWarmupRouteImport.update({
  id: '/warmup',
  path: '/warmup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeBasesIndexRoute =
  AuthenticatedKnowledgeBasesIndexRouteImport.update({
    id: '/knowledge-bases/',
    path: '/knowledge-bases/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKnowledgeBasesIdRoute =
  AuthenticatedKnowledgeBasesIdRouteImport.update({
    id: '/knowledge-bases/$id',
    path: '/knowledge-bases/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsNewRoute =
  AuthenticatedCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsIdRoute =
  AuthenticatedCampaignsIdRouteImport.update({
    id: '/campaigns/$id',
    path: '/campaigns/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/warmup': typeof AuthenticatedWarmupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/knowledge-bases/$id': typeof AuthenticatedKnowledgeBasesIdRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/knowledge-bases/': typeof AuthenticatedKnowledgeBasesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/warmup': typeof AuthenticatedWarmupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/knowledge-bases/$id': typeof AuthenticatedKnowledgeBasesIdRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/knowledge-bases': typeof AuthenticatedKnowledgeBasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/warmup': typeof AuthenticatedWarmupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/_authenticated/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/_authenticated/knowledge-bases/$id': typeof AuthenticatedKnowledgeBasesIdRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/knowledge-bases/': typeof AuthenticatedKnowledgeBasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/agents'
    | '/contacts'
    | '/inbox'
    | '/onboarding'
    | '/settings'
    | '/warmup'
    | '/auth/callback'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/knowledge-bases/$id'
    | '/campaigns/'
    | '/knowledge-bases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accounts'
    | '/agents'
    | '/contacts'
    | '/inbox'
    | '/onboarding'
    | '/settings'
    | '/warmup'
    | '/auth/callback'
    | '/'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/knowledge-bases/$id'
    | '/campaigns'
    | '/knowledge-bases'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/accounts'
    | '/_authenticated/agents'
    | '/_authenticated/contacts'
    | '/_authenticated/inbox'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/warmup'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/campaigns/$id'
    | '/_authenticated/campaigns/new'
    | '/_authenticated/knowledge-bases/$id'
    | '/_authenticated/campaigns/'
    | '/_authenticated/knowledge-bases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/warmup': {
      id: '/_authenticated/warmup'
      path: '/warmup'
      fullPath: '/warmup'
      preLoaderRoute: typeof AuthenticatedWarmupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge-bases/': {
      id: '/_authenticated/knowledge-bases/'
      path: '/knowledge-bases'
      fullPath: '/knowledge-bases/'
      preLoaderRoute: typeof AuthenticatedKnowledgeBasesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge-bases/$id': {
      id: '/_authenticated/knowledge-bases/$id'
      path: '/knowledge-bases/$id'
      fullPath: '/knowledge-bases/$id'
      preLoaderRoute: typeof AuthenticatedKnowledgeBasesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/new': {
      id: '/_authenticated/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthenticatedCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/$id': {
      id: '/_authenticated/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWarmupRoute: typeof AuthenticatedWarmupRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCampaignsIdRoute: typeof AuthenticatedCampaignsIdRoute
  AuthenticatedCampaignsNewRoute: typeof AuthenticatedCampaignsNewRoute
  AuthenticatedKnowledgeBasesIdRoute: typeof AuthenticatedKnowledgeBasesIdRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
  AuthenticatedKnowledgeBasesIndexRoute: typeof AuthenticatedKnowledgeBasesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWarmupRoute: AuthenticatedWarmupRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCampaignsIdRoute: AuthenticatedCampaignsIdRoute,
  AuthenticatedCampaignsNewRoute: AuthenticatedCampaignsNewRoute,
  AuthenticatedKnowledgeBasesIdRoute: AuthenticatedKnowledgeBasesIdRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
  AuthenticatedKnowledgeBasesIndexRoute: AuthenticatedKnowledgeBasesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
